### ISSUE TITLE
An error in the matlab file given in the example

### ISSUE THREAD

**Issue by zhaoyangluo** [chenmingzhang/SUTRASET#4]
When running read_ana.m in SUTRASET-master\examples\Fujimaki\MassarLoamy, an error occurs as follows:

Error using inpObj
Error: File: inpObj.m Line: 60 Column: 12
'cell' is already defined as a property.

Error in sl_read (line 9)
inp  = inpObj(fil.basename);

Error in read_ana

Could you please provide some help to me? Thanks a lot.

**Comment by chenmingzhang** [comment]
I think this is also resolved by downloading the latest version of SUTRALAB. we made default block reading of dataset 14 and 15 as yes, in order to accelerate the parsing of input file, as a return, no comments in allowed in dataset 14 and 15 in the inp file.

**Comment by zhaoyangluo** [comment]
Yes, it works. Thanks a lot.
